/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.DaoTrabajador;

import javax.swing.JOptionPane;

/**
 *
 * @author Andreita
 */
public class FrmTrabajador extends javax.swing.JFrame {
    DaoTrabajador lista = new DaoTrabajador();
    private boolean esNuevo;
    String numCedula = "";
    int posActual = 0;

    /**
     * Creates new form FrmTrabajador
     */
    public FrmTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNuevoT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnGuardarT = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnEliminarT = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnAnteriorT = new javax.swing.JButton();
        LbContador = new javax.swing.JLabel();
        btnSiguienteT = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnActualizarT = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TfApellido = new javax.swing.JTextField();
        TfNombre = new javax.swing.JTextField();
        TfNumCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TfSeguroSocial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TRABAJADOR");
        setPreferredSize(new java.awt.Dimension(700, 500));

        jToolBar1.setRollover(true);

        btnNuevoT.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\agregar-usuario.png")); // NOI18N
        btnNuevoT.setText("Nuevo");
        btnNuevoT.setFocusable(false);
        btnNuevoT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevoT);
        jToolBar1.add(jSeparator1);

        btnGuardarT.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\disquete.png")); // NOI18N
        btnGuardarT.setText("Guardar");
        btnGuardarT.setFocusable(false);
        btnGuardarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardarT);
        jToolBar1.add(jSeparator2);

        btnEliminarT.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\dejar-de-seguir.png")); // NOI18N
        btnEliminarT.setText("Eliminar");
        btnEliminarT.setFocusable(false);
        btnEliminarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminarT);
        jToolBar1.add(jSeparator3);

        btnAnteriorT.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\pista-anterior.png")); // NOI18N
        btnAnteriorT.setText("Anterior");
        btnAnteriorT.setFocusable(false);
        btnAnteriorT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnteriorT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnteriorT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAnteriorT);

        LbContador.setText("0 de 0");
        jToolBar1.add(LbContador);

        btnSiguienteT.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\siguiente-pista.png")); // NOI18N
        btnSiguienteT.setText("Siguiente");
        btnSiguienteT.setFocusable(false);
        btnSiguienteT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguienteT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguienteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSiguienteT);
        jToolBar1.add(jSeparator4);

        btnActualizarT.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\actualizar.png")); // NOI18N
        btnActualizarT.setText("Actualizar");
        btnActualizarT.setFocusable(false);
        btnActualizarT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizarT);
        jToolBar1.add(jSeparator5);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\usuario.png")); // NOI18N
        jButton1.setText("Modificar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Trabajador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Monospaced", 0, 13))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("N° de Cédula:");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("Apropiado:");

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("N° de Seguro Social: ");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Sí");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TfNumCedula)
                        .addComponent(TfApellido)
                        .addComponent(TfNombre)
                        .addComponent(TfSeguroSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TfNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfSeguroSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Downloads\\anterior.png")); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addGap(40, 40, 40)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnNuevoTActionPerformed

    private void btnGuardarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTActionPerformed
        // TODO add your handling code here:
              if(TfNombre.getText().equals(null)){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre", "Trabajador",
                    JOptionPane.WARNING_MESSAGE);
            this.TfNombre.requestFocus();
            return;
        }
        if(TfApellido.getText().equals(null)){
            JOptionPane.showMessageDialog(this, "Debe ingresar un apellido", "Trabajador",
                    JOptionPane.WARNING_MESSAGE);
            this.TfApellido.requestFocus();
            return;
        }
        if(TfNumCedula.getText().equals(null)){
            JOptionPane.showMessageDialog(this, "Debe ingresar un número de Cédula", "Trabajador",
                    JOptionPane.WARNING_MESSAGE);
            this.TfNumCedula.requestFocus();
            return;
         }
        if(TfSeguroSocial.getText().equals(null)){
            JOptionPane.showMessageDialog(this, "Debe ingresar un número de Seguro Social", "Trabajador",
                    JOptionPane.WARNING_MESSAGE);
            this.TfSeguroSocial.requestFocus();
            return;
        }
        int b=0;
        if (esNuevo ){
            b = lista.agregarTrabajador(TfNombre.getText(), TfApellido.getText(), TfNumCedula.getText(), TfSeguroSocial.getText());
            
        }
        if(b == 1){
            JOptionPane.showMessageDialog(this, "Registro guardado...", "Trabajador",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        this.mostrarEnTF(0);
        limpiar();
    }//GEN-LAST:event_btnGuardarTActionPerformed

    private void btnEliminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTActionPerformed
        // TODO add your handling code here:
           int resp = JOptionPane.showConfirmDialog(this, 
                "¿Realmente desea eliminar el Trabajador" + this.TfNombre.getText() + 
                " " + this.TfApellido.getText() + "?", "Trabajador",
                 JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == 0){
            int b = lista.eliminarTrabajador(numCedula);
            if(b==1){
                JOptionPane.showMessageDialog(this, "Registro eliminado satisfactoriamente"
                , "Trabajador", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Error inesperado, verifique y vuelva intentar",
                        "Trabajador", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarTActionPerformed

    private void btnAnteriorTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorTActionPerformed
        // TODO add your handling code here:
       if (posActual == 0) posActual = lista.getListaTrabajador().size();
        posActual--;
        this.mostrarEnTF(posActual);
    }//GEN-LAST:event_btnAnteriorTActionPerformed

    private void btnSiguienteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteTActionPerformed
        // TODO add your handling code here:
        posActual++;
        if (posActual == lista.getListaTrabajador().size()) posActual = 0;  
        this.mostrarEnTF(posActual);
    }//GEN-LAST:event_btnSiguienteTActionPerformed

    private void btnActualizarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTActionPerformed
        // TODO add your handling code here:
        String msn = lista.actualizarBD();
        JOptionPane.showMessageDialog(this, msn, "Actualizar Base de Datos",
                JOptionPane.INFORMATION_MESSAGE);
        posActual =0;
        mostrarEnTF(posActual);
    }//GEN-LAST:event_btnActualizarTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmModificarT mod = new FrmModificarT();
        mod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmInicio ini = new FrmInicio();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void mostrarEnTF(int fila){
        if(lista.getListaTrabajador().isEmpty()){
            TfNombre.setText(lista.getListaTrabajador().get(fila).getNombres());
            TfApellido.setText(lista.getListaTrabajador().get(fila).getApellidos());
            numCedula= lista.getListaTrabajador().get(fila).getNumCedula();
            esNuevo=false;

            int ultReg = lista.getListaTrabajador().size();
            LbContador.setText("" + (fila + 1) + " de " + ultReg);
            TfNombre.requestFocus();
        }else{
             limpiar();
        }
    }
    private void limpiar(){
        esNuevo = true;
        TfNombre.setText("");
        TfApellido.setText("");
        TfNumCedula.setText("");
        TfSeguroSocial.setText("");
        TfNombre.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbContador;
    private javax.swing.JTextField TfApellido;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JTextField TfNumCedula;
    private javax.swing.JTextField TfSeguroSocial;
    private javax.swing.JButton btnActualizarT;
    private javax.swing.JButton btnAnteriorT;
    private javax.swing.JButton btnEliminarT;
    private javax.swing.JButton btnGuardarT;
    private javax.swing.JButton btnNuevoT;
    private javax.swing.JButton btnSiguienteT;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
